import {
  ArrowCircleDownIcon,
  ArrowCircleUpIcon,
  BankIcon,
  BuildingIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  CheckCircleIcon,
  CheckIcon,
  ClockIcon,
  CopyIcon,
  EnvelopeSimpleIcon,
  EyeIcon,
  EyeSlashIcon,
  FilesIcon,
  FingerprintIcon,
  GearIcon,
  HouseLineIcon,
  KeyIcon,
  ListDashesIcon,
  ListIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  MoneyWavyIcon,
  NeedleIcon,
  PencilIcon,
  PhoneIcon,
  PlusIcon,
  QrCodeIcon,
  ScanSmileyIcon,
  ShareFatIcon,
  ShareNetworkIcon,
  SignOutIcon,
  SlidersHorizontalIcon,
  TranslateIcon,
  TrashIcon,
  UserCircleIcon,
  UserIcon,
  UsersThreeIcon,
  WarningIcon,
  WebhooksLogoIcon,
  XCircleIcon,
  XIcon,
} from 'phosphor-react-native';
import { PixIcon } from './custom';

export default {
  alert: WarningIcon,
  arrow_circle_down: ArrowCircleDownIcon,
  arrow_circle_up: ArrowCircleUpIcon,
  bank: BankIcon,
  building: BuildingIcon,
  charge: MoneyWavyIcon,
  check: CheckIcon,
  check_circle: CheckCircleIcon,
  chevron_down: CaretDownIcon,
  chevron_left: CaretLeftIcon,
  chevron_right: CaretRightIcon,
  chevron_up: CaretUpIcon,
  clipboard: CopyIcon,
  clock: ClockIcon,
  eye: EyeIcon,
  eye_slash: EyeSlashIcon,
  fingerprint: FingerprintIcon,
  home: HouseLineIcon,
  key: KeyIcon,
  gear: GearIcon,
  language: TranslateIcon,
  logout: SignOutIcon,
  mail: EnvelopeSimpleIcon,
  menu: ListIcon,
  minus: MinusIcon,
  network: NeedleIcon,
  pencil: PencilIcon,
  phone: PhoneIcon,
  plus: PlusIcon,
  qr_code: QrCodeIcon,
  scan_smile: ScanSmileyIcon,
  search: MagnifyingGlassIcon,
  share_fat: ShareFatIcon,
  share_network: ShareNetworkIcon,
  sliders_horizontal: SlidersHorizontalIcon,
  user: UserIcon,
  users: UsersThreeIcon,
  user_circle: UserCircleIcon,
  transactions: ListDashesIcon,
  trash: TrashIcon,
  webhook: WebhooksLogoIcon,
  xmark: XIcon,
  x_circle: XCircleIcon,
  statement: FilesIcon,
  pix: PixIcon,
};
