import {
  BankIcon,
  BuildingIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  CheckIcon,
  ClockIcon,
  CopyIcon,
  EnvelopeSimpleIcon,
  FilesIcon,
  HouseLineIcon,
  KeyIcon,
  ListDashesIcon,
  ListIcon,
  MagnifyingGlassIcon,
  MoneyWavyIcon,
  NeedleIcon,
  PencilIcon,
  PhoneIcon,
  PlusIcon,
  SignOutIcon,
  TranslateIcon,
  TrashIcon,
  UserCircleIcon,
  UserIcon,
  UsersThreeIcon,
  WarningIcon,
  WebhooksLogoIcon,
  XIcon,
} from 'phosphor-react-native';
import { PixIcon } from './custom';

export default {
  alert: WarningIcon,
  bank: BankIcon,
  building: BuildingIcon,
  charge: MoneyWavyIcon,
  check: CheckIcon,
  chevron_down: CaretDownIcon,
  chevron_left: CaretLeftIcon,
  chevron_right: CaretRightIcon,
  chevron_up: CaretUpIcon,
  clipboard: CopyIcon,
  clock: ClockIcon,
  home: HouseLineIcon,
  key: KeyIcon,
  language: TranslateIcon,
  logout: SignOutIcon,
  mail: EnvelopeSimpleIcon,
  menu: ListIcon,
  network: NeedleIcon,
  pencil: PencilIcon,
  phone: PhoneIcon,
  plus: PlusIcon,
  search: MagnifyingGlassIcon,
  user: UserIcon,
  users: UsersThreeIcon,
  user_circle: UserCircleIcon,
  transactions: ListDashesIcon,
  trash: TrashIcon,
  webhook: WebhooksLogoIcon,
  xmark: XIcon,
  statement: FilesIcon,
  pix: PixIcon,
};
